workflows:
  ios:
    name: iOS Workflow
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install
          
      - name: Build app
        script: |
          xcodebuild clean build -workspace Modularization.xcworkspace -scheme GamesApp -destination 'platform=iOS Simulator,name=iPhone 15'

      - name: Run tests
        script: |
          xcodebuild test -workspace Modularization.xcworkspace -scheme GamesApp -destination 'platform=iOS Simulator,name=iPhone 15'

    artifacts:
      - build/Build/Products/**/*.app
